# Exported from Render on 2026-05-02T19:55:56Z
version: "1"
projects:
- name: Camp Fit Fur Dogs
  environments:
  - name: Production
    services:
    - type: web
      name: campfitfurdogsapi
      runtime: docker
      repo: https://github.com/FrankJHughes/camp-fit-fur-dogs
      plan: starter
      region: oregon
      healthCheckPath: /health
      dockerContext: .
      dockerfilePath: ./Dockerfile
      autoDeployTrigger: commit
      previews:
        generation: automatic
      envVars:
        - key: ConnectionStrings__DefaultConnection
          fromSecret: production-db-connection-string
          previewValue: $PREVIEW_DB_CONNECTION_STRING
          sync: false

        - key: ASPNETCORE_ENVIRONMENT
          value: Production

        - key: Frontend__BaseUrl
          fromSecret: production-ui-base-url
          previewValue: $PREVIEW_UI_BASE_URL
          sync: false
