<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\Project.props" />

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Frank\Core\Domain\Frank.Core.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\src\Frank\Core\EntityFrameworkCore\Frank.Core.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\src\Frank\Identity\EntityFrameworkCore\Frank.Identity.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\TestUtilities\Frank.TestUtilities.csproj" />
  </ItemGroup>

</Project>
