// <auto-generated />
using System;
using CampFitFurDogs.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CampFitFurDogs.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260710125046_CffdInitialCreate")]
    partial class CffdInitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CampFitFurDogs.Domain.Dogs.Dog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sex");

                    b.HasKey("Id");

                    b.ToTable("dogs", (string)null);
                });

            modelBuilder.Entity("CampFitFurDogs.Domain.Dogs.Dog", b =>
                {
                    b.OwnsOne("CampFitFurDogs.Domain.Dogs.Breed", "Breed", b1 =>
                        {
                            b1.Property<Guid>("DogId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("breed");

                            b1.HasKey("DogId");

                            b1.ToTable("dogs");

                            b1.WithOwner()
                                .HasForeignKey("DogId");
                        });

                    b.OwnsOne("CampFitFurDogs.Domain.Dogs.DogName", "Name", b1 =>
                        {
                            b1.Property<Guid>("DogId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.HasKey("DogId");

                            b1.ToTable("dogs");

                            b1.WithOwner()
                                .HasForeignKey("DogId");
                        });

                    b.Navigation("Breed")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
