<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\Project.props" />

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Frank\Core\Application\Frank.Core.Application.csproj"/>
    <ProjectReference Include="..\..\..\..\src\Frank\Identity\Application\Frank.Identity.Application.csproj"/>
    <ProjectReference Include="..\..\..\..\tests\Frank\TestUtilities\Frank.TestUtilities.csproj"/>
  </ItemGroup>

</Project>
